### ISSUE TITLE
Consider moving all `obelisk` Node implementations out of workspace and into core package

### ISSUE THREAD

**Issue by alberthli** [Caltech-AMBER/obelisk#29]
The only thing that absolutely needs to be in a ROS2 executable file is a `main` function that can be registered as a console script. If we move these node implementations to the core package, it will also allow users to easily write derived classes from anything we provide in the default package. This would not be possible for any node implementations that we implement only in `obelisk_ws`.

**Comment by Zolkin1** [comment]
I believe this is what we are currently doing in api-setup. I'm linking to that PR to close this when merged.
