### ISSUE TITLE
`dummy_cpp` not found when running `ros-build` in `shielding-py`

### ISSUE THREAD

**Issue by gavin-hyl** [Caltech-AMBER/obelisk#43]
Ran `ros-build` from `api-setup` with all the C++ code merged in. switched branch to `shielding-py` and now we get the following error:
`error: can't copy '/home/gavin/caltech/surf2024/obelisk/obelisk_ws/build/obelisk_ros/config/dummy_cpp.yaml': doesn't exist or not a regular file`

Happens when building `obelisk-ros`.

**Comment by Zolkin1** [comment]
Note: builds when we add a empty `dummy_cpp` file.

**Comment by Zolkin1** [comment]
I believe this is a non-issue after `api-setup` was merged into main. closing for now.
